### ISSUE TITLE
 io_pdx_mesh failed Sellaris Automation import

### ISSUE THREAD

**Issue by vosperdw** [ross-g/io_pdx_mesh#11]
1. Installed io_pdx_mesh in Blender 2.82

2. Usage instructions were inaccurate for ver. 2.82.

3. Attempted to import Paradox Stellaris animation file "humanoid_01_battleship_frame_death.anim"

4. Operation failed.

5. Received error messages:
   "Automation import failed!"
   ""Missing unique armature required for animation: []
   "Traceback (most recent call last):"
      "File "C:\\Users\Dav\AppData\Roaming\Blender 
      Foundation\Blender\2.82\scripts\addons\io_pdx_mesh\pdx_blender\blender_ui.py",  
line 441, in execute timestart=self.int_start
      File "C:\\Users\Dav\AppData\Roaming\Blender 
      Foundation\Blender\2.82\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", in import_aminfile raise Runtime Error("Missing unique armature required for animation: {0}".format(matching_rigs))
     RuntimeError: Missing unique armature required for animation: []

    Location: <unknown location>:-1

Comments:  Blender version 2.82 has no "Tool Shelf".  The io_pdx_mesh menu is displayed by pressing the 'N' key.  .mesh files import just fine.

Very helpful plugin.  Thanks for your good work.

**Comment by ross-g** [comment]
Thanks for posing the issue, the wiki is indeed out of date! :) Hopefully I'll get time to update it and add some helpful information.

When you imported the animation file, did you have an empty scene or did you already import the correct mesh file? Animation files are just a description of movements, the error you have is reporting that Blender cannot find anything to apply the animation to (it needs something to animate).

You would need to import the mesh for this animation first (humanoid_01_battleship_frame.mesh) in order to import the animation.
