### ISSUE TITLE
v0.72 Stellaris: Mesh Import fails

### ISSUE THREAD

**Issue by Fragjacker** [ross-g/io_pdx_mesh#23]
Here we go again! The previous fix did indeed fix the locator issue, however today I ran into this issue:

![image](https://user-images.githubusercontent.com/19975052/99972987-8cc98880-2d9f-11eb-9629-ba8a76b430a3.png)

This one happens once I deleted some meshes and locators from a bigger master file to create mesh variations. The failing file can be found in the attachments. It also creates a corrupted in-game file with borked locators so it is kinda serious, again. 😁

[ascended_habitat_lvl1.zip](https://github.com/ross-g/io_pdx_mesh/files/5583575/ascended_habitat_lvl1.zip)

EDIT: I just tested and confirmed that this issue happens with v0.7 as well.

**Comment by Fragjacker** [comment]
After some further testing it turned out this issue only appears if there's not a single mesh in the scene that uses vertex groups with painted bone weights. As soon as I assigned some vertex groups to the meshes it started to work. However this is still an issue since binding meshes directly to bones without vertex groups causes the aforementioned problem.

**Comment by ross-g** [comment]
I really need an automated way of testing all possible combinations of data import/export before doing releases ... 😢 manual testing just doesn't cut through all the cases. Sorry for breaking your workflow again.

I can't put out a quick fix tonight sadly but if you're comfortable editing the addon yourself:

Change line 762:
* from ``bpy.data.meshes.remove(new_loc)``
* to ``bpy.data.objects.remove(new_loc)``

**Comment by ross-g** [comment]
As you say though, I don't think this would ever have worked even in the older versions. It just so happened that my last fix made this error on import rather than just skipping the bad data silently. What is it that you are doing to the scene to get it into a state where the exported file will error on import? 

Just to clarify - this is erroring here because it is trying to create a locator, and part of that locator data specifies a parent bone, which does not exist in the file being imported. So it's unable to create the locator as the parent bone forms part of the data needed to calculate the locators position.

**Comment by Fragjacker** [comment]
@ross-g Basically the scene contains a rig where some locators are parented to but not the meshes itself, not even vertex grouped. In the attachments I have uploaded the blender scene. Export it, then immediately re-import it again. It causes the aforementioned error.

[ascended_habitat_lvl1_failing.zip](https://github.com/ross-g/io_pdx_mesh/files/5585356/ascended_habitat_lvl1_failing.zip)

However even when binding all the meshes directly to any bone it still causes the same error. Only if the meshes use vertex groups to be parented to the bones, it works. However using vertex groups is most of the time overkill, when a simple bone link is more then enough.

**Comment by ross-g** [comment]
Implemented in 0.8 release. (364800cff10bdc822429ec73149cadcb05ef9710)
