### ISSUE TITLE
Surface normal changes on export/reimport

### ISSUE THREAD

**Issue by Nevla1** [ross-g/io_pdx_mesh#3]
First off, have almost no idea what I'm doing with this tool, took 3 hours to get it to even be able to export, and I don't even know if this is the texture. Anyway, the first file is the creation before exporting it as a .mesh file, and the second picture is the same creation after it has been exported and imported again. Any idea why it would change how it looks (and how to change it back if possible)?
![1](https://user-images.githubusercontent.com/51030183/65002723-074c6d80-d8aa-11e9-9d04-e030bb990fb6.PNG)
![2](https://user-images.githubusercontent.com/51030183/65002694-f1d74380-d8a9-11e9-943a-dfdeb4f7a223.PNG)

**Comment by ross-g** [comment]
Hey, what you're seeing there looks to be a complete loss of surface normals when you have re-imported. (ie none of the shading/smoothness information is there) You have a few options to fix this, either 'recalculate normals' or 'set from face'. This wiki page explains more.
https://docs.blender.org/manual/en/latest/modeling/meshes/editing/normals.html

I'm afraid I won't be able to look into what caused the issue from just screenshots, as I can't reproduce the problem. It would be great if you could upload the .blend file (before export) and the .mesh file (after export) so that I can investigate what went wrong!

**Comment by Nevla1** [comment]
Sorry it had to be in link form, github doesn't support .mesh files or .blend files. https://filebin.net/lv69mykz7pnq5ih6 Also I would recommend a tutorial for this tool, or if you would link me to a general one about PDXmeshes and rigs in blender that would be appreciated, thanks!

**Comment by ross-g** [comment]
@Nevla1 - I was going to verify that this was fixed for the next release, but can't find your example file in my test scenes. Any chance you could re-upload?
