### ISSUE TITLE
Texture not working properly on exported model?

### ISSUE THREAD

**Issue by ashjack** [ross-g/io_pdx_mesh#46]
I imported the model of CK3 eyes into Blender using this plugin, and changed the UV mapping to separate the eyes so each eye uses a different part of the texture. To do this, I doubled the width of the original texture from 512px to 1024px.

However, when I export the model, the extended part of the texture lacks any background, and I can't figure out why. In the image below, the white eye is correct, but the black eye should also be white.

![](https://i.imgur.com/ERkqMnU.png)

![](https://i.imgur.com/5cdGFca.png)

I'm not sure if this is being caused by this plugin, and I apologise if it isn't!

**Comment by ross-g** [comment]
Can you share the source and exported file, or at least a screenshot of the UVs (with both eyes selected in Blender). Otherwise it's pretty hard for me to tell what's going on from screenshots alone. 😄 

It might be something wrong with the export or it might be related to the particular shader used on the eyes.

The other method to try for the same result (ie texture eyes independently) would be to duplicate the original eye material, make no UV changes and then setup so you have two 512*512px textures and each eye has it's own material and texture.

**Comment by ashjack** [comment]
I don't believe I can set up two different textures as due to the way CK3 works (unless I'm mistaken) it requires a reference to one texture file for the model, so it has to be a combined texture.

I have uploaded the blend file and texture file, as well as the original .model file I imported, along with the exported one with the changed UVs.

Thank you for taking the time to investigate!

[Model.zip](https://github.com/ross-g/io_pdx_mesh/files/6211618/Model.zip)

**Comment by ross-g** [comment]
I'm thinking this is likely a setup issue (shader or texture) specific to what you're trying to do and not a problem with the exporter, as all of the data looks correct in the exported .mesh you attached. There's not really anything in the actual mesh which could cause the eye to go black while still displaying the iris correctly.

You can definitely reference multiple materials (and so multiple textures) for models in CK3, have a look at the mesh and asset setup for  **Crusader Kings III\game\gfx\models\units\infantry\unit_western_infantry_03** as an example.
