### ISSUE TITLE
skeleton export blender 2.92 and 2.83.3

### ISSUE THREAD

**Issue by StellarwhimsRepo** [ross-g/io_pdx_mesh#50]
save mesh does not appear to export skeleton when option is ticked.  it only seems to work if export skeleton is the only option ticked. all other objects are exported as expected with default options ticked, except for the skeleton.

**Comment by ross-g** [comment]
So this works fine for me, I think this is probably a lack of documentation rather than a bug.
With `Export mesh`  ticked, only skeletons that are linked to exported meshes are exported (ie bound via armature modifier). Without `Export mesh` ticked, all skeletons in the scene are exported.

So if you are exporting meshes, then unbound skeletons are ignored currently, and I can't really see a reason why you'd want meshes and unbound skeletons in an export. Happy to be told a reason though!

**Comment by StellarwhimsRepo** [comment]
i get the feeling blender creates a lot of "d'oh!" moments. my bad.

**Comment by ross-g** [comment]
I mean, this is how **I decided** the exporter should work, and it does that in Maya too so isn't really a Blender d'oh moment. But I can see how it would be confusing.

I'm open to suggestions if you think this could be done better or the export options be clearer.

**Comment by StellarwhimsRepo** [comment]
the functionality makes sense.  only thing i can think of about exporting skeletons by themselves is if for some reason you wanted to save skeleton and locator positions together. since it seems like if you are not careful, making a bone a parent of a mesh can mess with the mesh not translating perfectly and all your locators get misplaced. but if the locators are also bound to the armature / a bone then, barring further user error. things go smoother.
