### ISSUE TITLE
Unused material slots cause error upon exporting model

### ISSUE THREAD

**Issue by igorsmith1985** [ross-g/io_pdx_mesh#59]
Mesh export failed!
min() arg is an empty sequence
Traceback (most recent call last):
  File "C:\Users\natas\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_pdx_mesh\pdx_blender\blender_ui.py", line 510, in execute
    exp_selected=self.chk_selected,
  File "C:\Users\natas\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 1297, in export_meshfile
    mesh_info_dict, vert_ids = get_mesh_info(obj, mat_idx, split_verts)
  File "C:\Users\natas\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 341, in get_mesh_info
    mesh_dict["min"] = [min(x_vtx_pos), min(y_vtx_pos), min(z_vtx_pos)]
ValueError: min() arg is an empty sequence

location: <unknown location>:-1

------------------------
I get this upon exporting my model, ive exported models before so idk why its not working now, i have assigned the model and triangulated all faces.
I would really appreaciate it if you could get back to me on this!

**Comment by ross-g** [comment]
Basically this part of the code is trying to determine a bounding-box for part of your mesh, and it fails to determine the minimum here because it's not found any vertices.

Have you got a PDX material applied to your mesh? Have you got any empty material slots on your mesh?
I'm happy to take a look but it might mean you have to upload the model somewhere for me to investigate.

**Comment by igorsmith1985** [comment]
I have indeed applied the PDX material everywhere. Unless CTR+A somehow leaves out some faces...
Thank you alot for your quick response, i really appreciate it!

Heres the .blend file: https://www.file.io/download/wwxn8WodCAHq

**Comment by ross-g** [comment]
So the error is simple enough for me to fix 😄 it's happening due to the amount of unused material slots on your mesh.

I will fix this bug but for now you can simply run the `Object > Clean Up > Remove Unused Material Slots` command from the 3D viewports `Object` menu with your mesh selected. After doing this it exports fine without errors.

https://docs.blender.org/manual/en/latest/scene_layout/object/editing/cleanup.html#bpy-ops-object-material-slot-remove-unused

**Comment by igorsmith1985** [comment]
many many thanks! the export was successful this time!
